/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "filetransfer.h"

bool_t
xdr_send_file_res (XDR *xdrs, send_file_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		break;
	default:
		 if (!xdr_string (xdrs, &objp->send_file_res_u.errmsg, MAXLEN))
			 return FALSE;
		break;
	}
	return TRUE;
}

bool_t
xdr_retreive_file_res (XDR *xdrs, retreive_file_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_string (xdrs, &objp->retreive_file_res_u.data, MAXLEN))
			 return FALSE;
		break;
	default:
		 if (!xdr_string (xdrs, &objp->retreive_file_res_u.errmsg, MAXLEN))
			 return FALSE;
		break;
	}
	return TRUE;
}
