/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILETRANSFER_H_RPCGEN
#define _FILETRANSFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 1024

struct send_file_res {
	int errno;
	union {
		char *errmsg;
	} send_file_res_u;
};
typedef struct send_file_res send_file_res;

struct retreive_file_res {
	int errno;
	union {
		char *data;
		char *errmsg;
	} retreive_file_res_u;
};
typedef struct retreive_file_res retreive_file_res;

struct send_file_args {
	char *fname;
	char *fdata;
};
typedef struct send_file_args send_file_args;

#define FILETRANSFER_PROG 0x20000000
#define FILETRANSFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define retreive_file 1
extern  retreive_file_res * retreive_file_1(char **, CLIENT *);
extern  retreive_file_res * retreive_file_1_svc(char **, struct svc_req *);
#define send_file 2
extern  send_file_res * send_file_1(send_file_args *, CLIENT *);
extern  send_file_res * send_file_1_svc(send_file_args *, struct svc_req *);
extern int filetransfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define retreive_file 1
extern  retreive_file_res * retreive_file_1();
extern  retreive_file_res * retreive_file_1_svc();
#define send_file 2
extern  send_file_res * send_file_1();
extern  send_file_res * send_file_1_svc();
extern int filetransfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_send_file_res (XDR *, send_file_res*);
extern  bool_t xdr_retreive_file_res (XDR *, retreive_file_res*);
extern  bool_t xdr_send_file_args (XDR *, send_file_args*);

#else /* K&R C */
extern bool_t xdr_send_file_res ();
extern bool_t xdr_retreive_file_res ();
extern bool_t xdr_send_file_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILETRANSFER_H_RPCGEN */
